global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#andrej-sedov'
