kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: mBlo8L+uQY6kp9+HgCqdx6bqLDlPzCqQR+aTmIzQgCY=
      - identity: {}
