---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
    - secretName: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
              servicePort: {{ .Values.service.externalPort }}
